"""add_chatbot_color_theme

Revision ID: 35816820a63d
Revises: 4e99a8df00ff
Create Date: 2024-06-06 06:20:56.765105

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '35816820a63d'
down_revision = '4e99a8df00ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_color_theme', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chat_color_theme_inverted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('chat_color_theme_inverted')
        batch_op.drop_column('chat_color_theme')

    # ### end Alembic commands ###
